### ISSUE TITLE
Thanks for promoting Apollo!

### ISSUE THREAD

**Issue by Capri2014** [zhm-real/MotionPlanning#2]
Hi @zhm-real ,

Thanks for promoting Apollo! It is really glad to help the community and get attentions from the community. We recently added a few paper published related to Apollo PNC algorithms listed in "Related Paper" section of Planning and Control Module, https://github.com/ApolloAuto/apollo/tree/master/modules/planning https://github.com/ApolloAuto/apollo/tree/master/modules/control , was wondering if you could add those in the reference as well.

Thanks again,

**Comment by zhm-real** [comment]
I learned a lot from the two modules of Apollo, which are really good materials! I list the links of the two modules under recommended materials.
